## Predefined configuration sets - to be referenced below

# remote LLM authentication via API key stored in an env var
api_key_authentication: &api_key_authentication_settings
  type: env_var_secret
  env_var_name: OPENAI_API_KEY

# configuration for a local LLM service, launched using Ollama
local_llm: &local_llm_settings
  type: local
  model: 'granite4:7b-a1b-h'

# configuration for a remote LLM service, hosted in the cloud
remote_llm: &remote_llm_settings
  type: remote
  model: "gpt-4o"
  api_version: "2024-10-21"
  endpoint: "https://<your-resource-name>.openai.azure.com/"
  extra_headers:
  authentication:
    <<: *api_key_authentication_settings

# configuration for a local embeddings service, launched using Ollama
local_embeddings: &local_embeddings_settings
  type: local
  model: "snowflake-arctic-embed:m-long"

# configuration for a remote embeddings service, hosted in the cloud
remote_embeddings: &remote_embeddings_settings
  type: remote
  model: "text-embedding-3-small"
  api_version: "2024-10-21"
  endpoint: "https://<your-resource-name>.openai.azure.com/"
  extra_headers:
  authentication:
    <<: *api_key_authentication_settings

# configuration for a local vector store service
local_vectordb: &local_vectordb_settings
  type: local
  # choose between: cosine, euclidean_distance
  similarity: euclidean_distance

## App configuration settings

# minimum level for log messages to be displayed
# choose between:
# - debug
# - info
# - warning
# - error
# - fatal
log_level: info

# endpoint to send OpenTelemetry traces to e.g. Jaeger
observability_config:
  endpoint: http://localhost:4318/v1/traces

# choose one of the predefined LLM service configs from above:
# - local_llm_settings  - a locally-hosted service
# - remote_llm_settings - a cloud-hosted service
llm_config:
  <<: *local_llm_settings

# choose one of the predefined embeddings service configs from above:
# - local_embeddings_settings  - a locally-hosted service
# - remote_embeddings_settings - a cloud-hosted service
embeddings_config:
  <<: *local_embeddings_settings

# choose one of the predefined vector store service configs from above:
# - local_vectordb_settings - a locally-hosted service
vectordb_config:
  <<: *local_vectordb_settings
